all: hijo1 hijo2 multiA

hijo1: hijo1.c
	gcc -o hijo1 hijo1.c

hijo2: hijo2.c
	gcc -o hijo2 hijo2.c

multiA: multiA.c
	gcc -o multiA multiA.c

multiC: multiC.c
	gcc -o multiC multiC.c

multiD: multiD.c
	gcc -o multiD multiD.c

clean:
	rm hijo1 hijo2 multiA multiC multiD
