all:myPs myPs_v0 myPs2 myPs3

myPs:myPs.c
	gcc -o myPs myPs.c
myPs_v0:myPs_v0.c
	gcc -o myPs_v0 myPs_v0.c
myPs2:myPs2.c
	gcc -o myPs2 myPs2.c
myPs3:myPs3.c
		gcc -o myPs3 myPs3.c

clean:
	rm myPs myPs_v myPs_v0 myPs2 myPs3
